server:
  error:
    path: /error
    whitelabel:
      enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
  datasource:
    password: postgrespw
    username: postgres
    url: jdbc:postgresql://localhost:49153/krohabd
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  recipientEmail: ${MAIL_RECIPIENT}

admin:
  userName: ${ROPOT_NAME}
  password: ${ROPOT_PASSWORD}